image:
  file: .gitpod.Dockerfile
  
tasks:
  - name: init dev env
  - init: >
      npm install --also-dev
      poetry install
    

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python