image:
  file: .gitpod.Dockerfile

tasks:
  - name: init npm
    init: npm install --also-dev
  - name: init python
    init: poetry install

vscode:
  extensions:
    - ms-python.python
    - esbenp.prettier-vscode
