image:
  file: .gitpod.Dockerfile

tasks:
  - name: init dev environment
    init: >
      npm install --also-dev &&
      poetry install

vscode:
  extensions:
    - ms-python.python
    - esbenp.prettier-vscode
